export {
  DEMO_DEV_EMAIL_DEFAULT,
  DEMO_TENANT_BRAND,
  DEMO_TENANT_COUNTRY,
  DEMO_TENANT_LEGAL_NAME,
  DEMO_TENANT_SLUG,
  DEMO_TENANT_TAGLINE,
  LEGACY_DEMO_TENANT_SLUG,
} from "../src/lib/demo-tenant";
