import {
  Building2,
  ChartColumn,
  ClipboardList,
  Factory,
  FileText,
  Folder,
  Inbox,
  LayoutDashboard,
  Mail,
  Microscope,
  Package,
  Settings,
  ShieldCheck,
  ShoppingBag,
  Sparkles,
  UserPlus,
  Users,
  Warehouse,
  type LucideIcon,
} from "lucide-react";

import type { NavIconName } from "@/lib/mock/navigation";

export const navIcons: Record<NavIconName, LucideIcon> = {
  "layout-dashboard": LayoutDashboard,
  sparkles: Sparkles,
  "user-plus": UserPlus,
  "building-2": Building2,
  inbox: Inbox,
  "file-text": FileText,
  "shopping-bag": ShoppingBag,
  package: Package,
  microscope: Microscope,
  folder: Folder,
  "chart-column": ChartColumn,
  warehouse: Warehouse,
  factory: Factory,
  "shield-check": ShieldCheck,
  mail: Mail,
  users: Users,
  settings: Settings,
  "clipboard-list": ClipboardList,
};
